name: Test React App
on: push
jobs:
  test_application:
    runs_on: ubuntu_latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: test application
        run: npm run test
